AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/*"
    - "config/**/*"
    - "Gemfile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

##################### Style #######################

Style/Documentation:
  Enabled: false

##################### Metrics #######################
Metrics/BlockLength:
  Enabled: false