AllCops:
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/*"
    - "vendor/**/*"
    - "config/**/*"
    - "Gemfile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

##################### Style #######################

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

##################### Metrics #######################
Metrics/BlockLength:
  Enabled: false

##################### Airbnb #######################
Airbnb/ModuleMethodInWrongFile:
  Enabled: false
